import { createHash } from "node:crypto";

/**
 * The runtime and importer intentionally share one small, vendor-neutral event
 * shape.  Keep this union closed: adding an operation or outcome is a reviewable
 * API change rather than an arbitrary label reaching a log sink.
 */
export type ConversationObservationOperation =
  | "run"
  | "append"
  | "finish"
  | "replay"
  | "connect"
  | "resync"
  | "stop"
  | "lease"
  | "activeRuns"
  | "persistence"
  | "inventory"
  | "source"
  | "publication"
  | "import";

export type ConversationObservationOutcome =
  | "started"
  | "progress"
  | "completed"
  | "failed"
  | "paused"
  | "cancelled"
  | "blocked"
  | "unchanged"
  | "validated"
  | "staged"
  | "retrying"
  | "received"
  | "selected"
  | "published"
  | "excluded"
  | "sourceChanged"
  | "discovered"
  | "pages"
  | "pairs"
  | "requested"
  | "settled"
  | "conflict"
  | "lost"
  | "expired"
  | "interrupted";

export type ConversationObservationPhase =
  | "inventory"
  | "awaiting_confirmation"
  | "importing"
  | "paused"
  | "cancelled"
  | "completed"
  | "completed_with_gaps"
  | "failed";

export type ConversationObservationGap =
  | "sequence"
  | "connect"
  | "resync"
  | "lease"
  | "stop"
  | "startup"
  | "persistence"
  | "not-found"
  | "unavailable"
  | "truncated"
  | "decode-error"
  | "no-snapshot"
  | "skipped-deltas"
  | "debug-not-applicable"
  | "missing-asset"
  | "ownership"
  | "source-changed"
  | "history-only";

export type ConversationObservationError =
  | "persistence"
  | "lease"
  | "conflict"
  | "authorization"
  | "replay"
  | "stop"
  | "startup"
  | "unknown"
  | "source-auth"
  | "source-transport"
  | "source-protocol";

export type ConversationObservation = {
  subsystem: "runtime" | "import";
  operation: ConversationObservationOperation;
  outcome: ConversationObservationOutcome;
  /** Generated by observeConversation; caller-provided timestamps are ignored. */
  timestampMs: number;
  phase?: ConversationObservationPhase;
  correlation?: {
    threadId?: string;
    runId?: string;
    jobId?: string;
  };
  latencyMs?: number;
  lag?: number;
  count?: number;
  httpStatus?: number;
  retry?: number;
  gap?: ConversationObservationGap;
  error?: ConversationObservationError;
};

export type ConversationObserver = (
  observation: Readonly<ConversationObservation>,
) => void | Promise<void>;

const operations = new Set<ConversationObservationOperation>([
  "run",
  "append",
  "finish",
  "replay",
  "connect",
  "resync",
  "stop",
  "lease",
  "activeRuns",
  "persistence",
  "inventory",
  "source",
  "publication",
  "import",
]);
const outcomes = new Set<ConversationObservationOutcome>([
  "started",
  "progress",
  "completed",
  "failed",
  "paused",
  "cancelled",
  "blocked",
  "unchanged",
  "validated",
  "staged",
  "retrying",
  "received",
  "selected",
  "published",
  "excluded",
  "sourceChanged",
  "discovered",
  "pages",
  "pairs",
  "requested",
  "settled",
  "conflict",
  "lost",
  "expired",
  "interrupted",
]);
const phases = new Set<ConversationObservationPhase>([
  "inventory",
  "awaiting_confirmation",
  "importing",
  "paused",
  "cancelled",
  "completed",
  "completed_with_gaps",
  "failed",
]);
const gaps = new Set<ConversationObservationGap>([
  "sequence",
  "connect",
  "resync",
  "lease",
  "stop",
  "startup",
  "persistence",
  "not-found",
  "unavailable",
  "truncated",
  "decode-error",
  "no-snapshot",
  "skipped-deltas",
  "debug-not-applicable",
  "missing-asset",
  "ownership",
  "source-changed",
  "history-only",
]);
const errors = new Set<ConversationObservationError>([
  "persistence",
  "lease",
  "conflict",
  "authorization",
  "replay",
  "stop",
  "startup",
  "unknown",
  "source-auth",
  "source-transport",
  "source-protocol",
]);

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function member<T extends string>(
  set: ReadonlySet<T>,
  value: unknown,
): T | undefined {
  return typeof value === "string" && set.has(value as T)
    ? (value as T)
    : undefined;
}

function measurement(value: unknown, integer = false): number | undefined {
  if (typeof value !== "number" || !Number.isFinite(value) || value < 0)
    return undefined;
  if (integer && !Number.isInteger(value)) return undefined;
  return value;
}

function hashCorrelation(value: unknown): string | undefined {
  if (typeof value !== "string") return undefined;
  return createHash("sha256").update(value, "utf8").digest("hex");
}

/**
 * Delivers one redacted, whitelisted observation.  The callback is deliberately
 * best-effort: telemetry must never change conversation control flow.
 */
export function observeConversation(
  observer: ConversationObserver | undefined,
  observation: unknown,
): void {
  if (!observer || !isRecord(observation)) return;

  const subsystem =
    observation.subsystem === "runtime" || observation.subsystem === "import"
      ? observation.subsystem
      : undefined;
  const operation = member(operations, observation.operation);
  const outcome = member(outcomes, observation.outcome);
  if (!subsystem || !operation || !outcome) return;

  const output: ConversationObservation = {
    subsystem,
    operation,
    outcome,
    timestampMs: Date.now(),
  };
  const phase = member(phases, observation.phase);
  if (phase) output.phase = phase;
  if (isRecord(observation.correlation)) {
    const redactedCorrelation: {
      threadId?: string;
      runId?: string;
      jobId?: string;
    } = {};
    const threadId = hashCorrelation(observation.correlation.threadId);
    const runId = hashCorrelation(observation.correlation.runId);
    const jobId = hashCorrelation(observation.correlation.jobId);
    if (threadId) redactedCorrelation.threadId = threadId;
    if (runId) redactedCorrelation.runId = runId;
    if (jobId) redactedCorrelation.jobId = jobId;
    if (Object.keys(redactedCorrelation).length > 0)
      output.correlation = redactedCorrelation;
  }

  const latencyMs = measurement(observation.latencyMs);
  if (latencyMs !== undefined) output.latencyMs = latencyMs;
  const lag = measurement(observation.lag, true);
  if (lag !== undefined) output.lag = lag;
  const count = measurement(observation.count, true);
  if (count !== undefined) output.count = count;
  const httpStatus = measurement(observation.httpStatus, true);
  if (httpStatus !== undefined && httpStatus >= 100 && httpStatus <= 599)
    output.httpStatus = httpStatus;
  const retry = measurement(observation.retry, true);
  if (retry !== undefined) output.retry = retry;
  const gap = member(gaps, observation.gap);
  if (gap) output.gap = gap;
  const error = member(errors, observation.error);
  if (error) output.error = error;

  try {
    let result: void | Promise<void>;
    try {
      result = observer(output);
    } catch {
      return;
    }
    void Promise.resolve(result).catch(() => undefined);
  } catch {
    // A malformed thenable or callback must not affect the caller.
  }
}
